kernel-headers: install isa-rev.h on mips to fix lzma-lader on linux 6.1
Since kernel 5.17+ the mips asm.h includes isa-rev.h, which itself was
added 4.17. Without it, lzma-loader will fail to build:

     make[3] -C target/linux compile
    make[5]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
    In file included from head.S:22:
    .../staging_dir/toolchain-mips_mips32_gcc-12.3.0_musl/include/asm/asm.h:22:10: fatal error: asm/isa-rev.h: No such file or directory
       22 | #include <asm/isa-rev.h>
          |          ^~~~~~~~~~~~~~~
    compilation terminated.
    make[6]: *** [Makefile:64: head.o] Error 1
    make[5]: *** [Makefile:345: compile] Error 2
    make[4]: *** [Makefile:24: compile] Error 2
    make[3]: *** [Makefile:11: compile] Error 2
        ERROR: target/linux failed to build.

So add the file to the files to install. We can do that unconditionally,
since the oldest supported kernel 5.15 already includes it, even it if
does not need it.

Signed-off-by: Jonas Gorski <jonas.gorski@gmail.com>